--- #YAML:1.0
name:               Template-Simple
version:            0.06
abstract:           A simple and very fast template module
author:
    - Uri Guttman <uri@sysarch.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Slurp:  0
    Test::More:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
